<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-CP7G377U" ignored="1" name="EmpTests(failed)" tests="4" failures="1" timestamp="2021-06-09T17:15:39 IST" time="67.198" errors="0">
  <testcase name="login" time="13.903" classname="com.suycorp.tests.EmpTests"/>
  <testcase name="addEmps" time="16.88" classname="com.suycorp.tests.EmpTests"/>
  <testcase name="editAddedEmpAndVerify" time="12.833" classname="com.suycorp.tests.EmpTests">
    <failure type="java.lang.AssertionError" message="Failed in editAddedEmpAndVerify">
      <![CDATA[java.lang.AssertionError: Failed in editAddedEmpAndVerify
at com.suycorp.tests.EmpTests.editAddedEmpAndVerify(EmpTests.java:124)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- editAddedEmpAndVerify -->
  <testcase name="delAddedEmps" time="17.444" classname="com.suycorp.tests.EmpTests"/>
  <testcase name="delMultiEmp" time="0.0" classname="com.suycorp.tests.EmpTests">
    <ignored/>
  </testcase> <!-- delMultiEmp -->
</testsuite> <!-- EmpTests(failed) -->
